<h1>Cadastro de Games</h1>

<form action="<?php echo $this->baseUrl('game/gravar'); ?>" method="post" enctype="multipart/form-data">
	<input type="hidden" name="id_game" value="<?php echo $this->row['id_game']; ?>" />
	
	<div class="form-group">
	    <label for="nome_game">Nome</label>
	    <input type="text" class="form-control" id="nome_game" name="nome_game" value="<?php echo $this->row['nome_game']; ?>">
	</div>
	
	<div class="form-group">
	    <label for="descricao_game">Descrição</label>
			<textarea rows="3" cols="10" class="form-control" id="descricao_game" name="descricao_game" >
<?php echo $this->row['descricao_game']; ?>
			</textarea>	
	</div>
	
	<div class="form-group">
	    <label for="quantidade">Quantidade</label>
	    <input type="number" class="form-control" id="quantidade" name="quantidade" value="<?php echo $this->row['quantidade']; ?>">
	</div>	
	<?php if(!empty($this->row['disponibilidade'])) {?>  
		<div class="checkbox">
		  	<label for="disponibilidade"><input type="checkbox" name="disponibilidade" id="disponibilidade" checked="checked" value="<?php echo $this->row['disponibilidade']; ?>">Disponibilidade</label>
		</div>
	<?php }else {?>
		<div class="checkbox">
		  	<label for="disponibilidade"><input type="checkbox" name="disponibilidade" id="disponibilidade" value="<?php echo $this->row['disponibilidade']; ?>">Disponibilidade</label>
		</div>
	<?php }?>
	
	<div class="form-group">
	    <label for="console">Console</label>
    	<select class="form-control" id="console" name="id_console">
    		<option value="">Selecione</option>
    		<?php foreach($this->rowSetConsole as $rowConsole){ ?>
    			<option <?php echo $this->row['id_console'] == $rowConsole['id_console'] ? 'selected="selected"' : ''; ?> value="<?php echo $rowConsole['id_console']; ?>"><?php echo $rowConsole['nome_console']; ?></option>
    		<?php } ?>
    	</select>
	</div>
	
	<div class="form-group">
	    <label for="genero">Genero</label>
    	<select class="form-control" id="genero" name="id_genero">
    		<option value="">Selecione</option>
    		<?php foreach($this->rowSetGenero as $rowGenero){ ?>
    			<option <?php echo $this->row['id_genero'] == $rowGenero['id_genero'] ? 'selected="selected"' : ''; ?> value="<?php echo $rowGenero['id_genero']; ?>"><?php echo $rowGenero['nome_genero']; ?></option>
    		<?php } ?>
    	</select>
	</div>
	
	<div class="form-group">
	    <label for="foto">Foto</label>
	    <input type="file" class="form-control" id="foto" name="foto" value="<?php echo $this->row['foto']; ?>">
	</div>
	
	<div class="text-center">
		<input type="submit" value="Enviar" class="btn btn-success" />
		<a href="<?php echo $this->baseUrl('game/index'); ?>" class="btn btn-danger" >Voltar</a>
	</div>
</form>
<script>
function marcardesmarcar() {
    $('.marcar').each(function () {
        if (this.checked) this.checked = false;
        else this.checked = true;
    });
}
</script>