<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8" />
    <title>Locadora Legends</title>

    <link href="<?php echo $this->baseUrl('js/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet">

    <!-- Mainly scripts -->
    <script src="<?php echo $this->baseUrl('js/jquery-2.2.3.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('js/bootstrap/js/bootstrap.min.js'); ?>"></script>
    <script src="<?php echo $this->baseUrl('js/jquery.maskedinput.js'); ?>"></script>
	<script src="<?php echo $this->baseUrl('js/jquery.maskMoney.min.js'); ?>"></script>
	
	<script type="text/javascript">
		$(function(){
		 $("#valor").maskMoney({symbol:'R$ ', 
		showSymbol:true, decimal:'.', symbolStay: true});
		 })
	</script>

	<script type="text/javascript"> 
		jQuery(function($){
		    $("#tel_celular").mask("(99) 9999-9999?9 ");
		    $("#tel_fixo").mask("(99) 9999-9999?9 ");
		    $("#cpf").mask("999.999.999-99");
		    $("#cep").mask("99999-999");
		    
		})
	</script> 
    <?php echo $this->headScript(); ?>
</head>

<body>

 <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Locadora Legends</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Principal</a></li>
			    <li><a href="<?php echo $this->baseUrl('cliente/index'); ?>">Clientes</a></li>
	            <li><a href="<?php echo $this->baseUrl('console/index'); ?>">Consoles</a></li>
	            <li><a href="<?php echo $this->baseUrl('genero/index'); ?>">Generos</a></li>
	            <li><a href="<?php echo $this->baseUrl('game/index'); ?>">Games</a></li>
			    <li><a href="<?php echo $this->baseUrl('locacao/index'); ?>">Locações</a></li>
          </ul>
          <!--  <ul class="nav navbar-nav navbar-right">
            	<li><a>Bem vindo, <?php echo $_SESSION['nome']?></a></li>    
	            	<li><a href="<?php echo $this->baseUrl('funcionario/formulario/id_funcionario/' . $_SESSION['id_funcionario']); ?>">
	            	<img src="<?php echo $this->baseUrl('img/fotos/' . $_SESSION['foto']); ?>" width="60px"/></a></li> 
            	<li><a href="<?php echo $this->baseUrl('funcionario/logout'); ?>">Sair</a></li>    
            	<li><a href="<?php echo $this->baseUrl('funcionario/login'); ?>">Login</a></li>
          </ul>-->
        </div><!--/.nav-collapse -->
      </div>
    </nav>
	
	<div class="container"  style="margin-top: 60px;">
    	<?php echo $this->layout()->content; ?>
	</div>
	
<style type="text/css">
.navbar {
    width:100%;
    height:48px;
    margin-top:-6px;
    position:relative;
    background-color: rgb(0, 0, 139);
    border-radius: 0px 0px 15px 15px;
}  
body{
	background-color: rgb(176, 196, 222);
}  
</style>
    
</body>
</html>
